### PR TITLE
added pre-commit hook to project

### PR DESCRIPTION
**Pull request by xinwei89**
added pre-commit hook to project

### CODE REVIEW

**Review by sahandv — CHANGES_REQUESTED** [review]
The config file looks good to me. Can you also add the following lines to a `setup.cfg` file in the project directory? Without it, there will be conflicts between some of these tools.

```
[flake8]
ignore = E501, W503, E203, E265

[isort]
profile = black
```

**Comment by xinwei89** [comment]
Thanks, should I also add a [metadata] section like the conversion repo in the `setup.cfg` file?

**Comment by sahandv** [comment]
> Thanks, should I also add a [metadata] section like the conversion repo in the `setup.cfg` file?

I guess it shouldn't be a bad idea to have a draft project description. For example, we can have the author, name, URL, and/or any other item you think fits the project.

**Comment by xinwei89** [comment]
Okay, I've just copied in what you have for now.

**Review by sahandv — APPROVED** [review]
These changes look good to me. Thanks for the additions.

**Pull request merged**
